sudo: required
services:
  - docker

language: node_js
node_js:
  - '6'

cache:
  directories:
  - node_modules
  - "$HOME/.cache/bower"
  - "$HOME/.npm"

before_install:
  - npm install -g grunt-cli bower

script:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      export OPENSENSEMAP_API_URL=$OPENSENSEMAP_API_URL_MASTER;
      export OPENSENSEMAP_MAPTILES_URL=$OPENSENSEMAP_MAPTILES_URL_MASTER;
    fi
  - npm run build
  - docker build -t $IMAGE_NAME:$TRAVIS_BRANCH .

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

  - docker pull $IMAGE_NAME:$TRAVIS_BRANCH
  - docker tag $IMAGE_NAME:$TRAVIS_BRANCH $IMAGE_NAME:$TRAVIS_BRANCH-rollback
  - docker push $IMAGE_NAME:$TRAVIS_BRANCH-rollback

  - docker tag $IMAGE_NAME:$TRAVIS_BRANCH-temp $IMAGE_NAME:$TRAVIS_BRANCH
  - docker push $IMAGE_NAME:$TRAVIS_BRANCH
